import { apiFetch, DASHBOARD_TOKEN_KEY } from '@/lib/apiConfig';

export type Row = Record<string, unknown> & { id?: number };
export type ListResponse<T = Row> = { items: T[]; meta?: { page?: number; limit?: number; total?: number; pages?: number } };

function token() { return typeof window === 'undefined' ? '' : localStorage.getItem(DASHBOARD_TOKEN_KEY) || ''; }
function request<T>(path: string, init: RequestInit = {}) { return apiFetch<T>(path, init, { token: token() }); }
function post<T>(path: string, body: unknown) { return request<T>(path, { method: 'POST', body: JSON.stringify(body ?? {}) }); }
function put<T>(path: string, body: unknown) { return request<T>(path, { method: 'PUT', body: JSON.stringify(body ?? {}) }); }
function del<T>(path: string) { return request<T>(path, { method: 'DELETE' }); }
function query(params: Record<string, string | number | undefined>) {
  const q = new URLSearchParams(); Object.entries(params).forEach(([k,v]) => { if (v !== undefined && v !== '') q.set(k,String(v)); });
  return q.toString() ? `?${q}` : '';
}

export const utilidadesV15Api = {
  me: () => request<Row>('/utilidades/me'),
  portfolio: () => request<Row>('/utilidades/portfolio'),
  readiness: () => request<Row>('/utilidades/readiness'),
  scopes: () => request<ListResponse>('/utilidades/scopes'),
  scopeOptions: () => request<Row>('/utilidades/scopes/options'),
  createScope: (data:Row) => post<Row>('/utilidades/scopes',data),
  deleteScope: (id:number) => del<Row>(`/utilidades/scopes/${id}`),
  locations: (p: Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/locations${query(p)}`),
  createLocation: (data: Row) => post<Row>('/utilidades/locations', data),
  updateLocation: (id:number,data:Row) => put<Row>(`/utilidades/locations/${id}`,data),
  workspace: (id:number) => request<Row>(`/utilidades/locations/${id}/workspace`),
  clients: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/clients${query(p)}`),
  clientDetail: (id:number) => request<Row>(`/utilidades/clients/${id}`),
  agencies: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/agencies${query(p)}`),
  agencyDetail: (id:number) => request<Row>(`/utilidades/agencies/${id}`),
  alerts: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/alerts${query(p)}`),
  createAlert: (data:Row) => post<Row>('/utilidades/alerts',data),
  ackAlert: (id:number) => post<Row>(`/utilidades/alerts/${id}/ack`,{}),
  resolveAlert: (id:number) => post<Row>(`/utilidades/alerts/${id}/resolve`,{}),
  reports: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/reports${query(p)}`),
  runReport: (data:Row) => post<Row>('/utilidades/reports',data),
  findings: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/findings${query(p)}`),
  createFinding: (data:Row) => post<Row>('/utilidades/findings',data),
  actions: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/actions${query(p)}`),
  createAction: (data:Row) => post<Row>('/utilidades/actions',data),
  updateAction: (id:number,data:Row) => put<Row>(`/utilidades/actions/${id}`,data),
  transitionAction: (id:number,status:string,comments?:string) => post<Row>(`/utilidades/actions/${id}/status`,{status,comments}),
  market: (actionId?:number) => request<Row>(`/utilidades/market/services${actionId?`?actionId=${actionId}`:''}`),
  marketSummary: () => request<Row>('/utilidades/market/summary'),
  createQuote: (data:Row) => post<Row>('/utilidades/quotes',data),
  approveQuote: (id:number) => post<Row>(`/utilidades/quotes/${id}/approve`,{}),
  workOrders: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/work-orders${query(p)}`),
  workOrder: (id:number) => request<Row>(`/utilidades/work-orders/${id}`),
  createWorkOrder: (data:Row) => post<Row>('/utilidades/work-orders',data),
  updateWorkOrder: (id:number,data:Row) => put<Row>(`/utilidades/work-orders/${id}`,data),
  transitionWorkOrder: (id:number,status:string,comments?:string) => post<Row>(`/utilidades/work-orders/${id}/status`,{status,comments}),
  addMilestone: (id:number,data:Row) => post<Row>(`/utilidades/work-orders/${id}/milestones`,data),
  completeMilestone: (id:number,milestoneId:number) => post<Row>(`/utilidades/work-orders/${id}/milestones/${milestoneId}/complete`,{}),
  addEvidence: (id:number,data:Row) => post<Row>(`/utilidades/work-orders/${id}/evidence`,data),
  approveWorkOrder: (id:number,data:Row) => post<Row>(`/utilidades/work-orders/${id}/approval`,data),
  reviewCampaigns: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/campaigns/reviews${query(p)}`),
  createReviewCampaign: (data:Row) => post<Row>('/utilidades/campaigns/reviews',data),
  reviewCampaign: (id:number) => request<Row>(`/utilidades/campaigns/reviews/${id}`),
  addReviewRecipient: (id:number,data:Row) => post<Row>(`/utilidades/campaigns/reviews/${id}/recipients`,data),
  updateReviewRecipient: (id:number,recipientId:number,data:Row) => put<Row>(`/utilidades/campaigns/reviews/${id}/recipients/${recipientId}`,data),
  executeReviewCampaign: (id:number,mode:'manual'|'webhook'='manual') => post<Row>(`/utilidades/campaigns/reviews/${id}/execute`,{mode}),
  updateReviewCampaign: (id:number,data:Row) => put<Row>(`/utilidades/campaigns/reviews/${id}`,data),
  citationCampaigns: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/campaigns/citations${query(p)}`),
  createCitationCampaign: (data:Row) => post<Row>('/utilidades/campaigns/citations',data),
  citationCampaign: (id:number) => request<Row>(`/utilidades/campaigns/citations/${id}`),
  addCitationItem: (id:number,data:Row) => post<Row>(`/utilidades/campaigns/citations/${id}/items`,data),
  updateCitationItem: (id:number,itemId:number,data:Row) => put<Row>(`/utilidades/campaigns/citations/${id}/items/${itemId}`,data),
  updateCitationCampaign: (id:number,data:Row) => put<Row>(`/utilidades/campaigns/citations/${id}`,data),
  gbpPosts: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/gbp-posts${query(p)}`),
  createGbpPost: (data:Row) => post<Row>('/utilidades/gbp-posts',data),
  updateGbpPost: (id:number,data:Row) => put<Row>(`/utilidades/gbp-posts/${id}`,data),
  prospects: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/prospects${query(p)}`),
  createProspect: (data:Row) => post<Row>('/utilidades/prospects',data),
  updateProspect: (id:number,data:Row) => put<Row>(`/utilidades/prospects/${id}`,data),
  whiteLabels: () => request<ListResponse>('/utilidades/white-label'),
  upsertWhiteLabel: (data:Row) => post<Row>('/utilidades/white-label',data),
  kpis: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/kpis${query(p)}`),
  createKpi: (data:Row) => post<Row>('/utilidades/kpis',data),
  cases: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/cases${query(p)}`),
  caseDetail: (id:number) => request<Row>(`/utilidades/cases/${id}`),
  createCase: (data:Row) => post<Row>('/utilidades/cases',data),
  updateCase: (id:number,data:Row) => put<Row>(`/utilidades/cases/${id}`,data),
  addCaseActivity: (id:number,data:Row) => post<Row>(`/utilidades/cases/${id}/activities`,data),
  integrations: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/integrations${query(p)}`),
  upsertIntegration: (data:Row) => post<Row>('/utilidades/integrations',data),
  syncIntegration: (id:number) => post<Row>(`/utilidades/integrations/${id}/sync`,{}),
  providerSnapshots: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/provider-snapshots${query(p)}`),
  importProviderSnapshot: (data:Row) => post<Row>('/utilidades/provider-snapshots',data),
  addCreditMovement: (data:Row) => post<Row>('/utilidades/credits',data),
  audit: (p:Record<string,string|number|undefined>={}) => request<ListResponse>(`/utilidades/audit${query(p)}`),

  rankTracker: (locationId:number) => request<Row>(`/utilidades/rank-tracker/${locationId}`),
  rankTrackerRun: (locationId:number) => post<Row>(`/utilidades/rank-tracker/${locationId}/run`,{}),
  rankTrackerAddKeywords: (locationId:number,keywords:Array<Record<string,string>>) => post<Row>(`/utilidades/rank-tracker/${locationId}/keywords`,{keywords}),
  rankTrackerDeleteKeyword: (locationId:number,keyword:string) => request<Row>(`/utilidades/rank-tracker/${locationId}/keywords`,{method:'DELETE',body:JSON.stringify({keyword})}),
  rankTrackerSchedule: (locationId:number,schedule:Record<string,string>) => post<Row>(`/utilidades/rank-tracker/${locationId}/schedule`,schedule),
  rankTrackerCompetitors: (locationId:number,competitors:string[]) => post<Row>(`/utilidades/rank-tracker/${locationId}/competitors`,{competitors}),
  searchGrid: (locationId:number) => request<Row>(`/utilidades/search-grid/${locationId}`),
  searchGridRun: (locationId:number) => post<Row>(`/utilidades/search-grid/${locationId}/run`,{}),
  searchGridConfig: (locationId:number,config:Row) => post<Row>(`/utilidades/search-grid/${locationId}/config`,config),
  searchGridPoint: (locationId:number,pointKey:string,active:boolean) => post<Row>(`/utilidades/search-grid/${locationId}/point`,{pointKey,active}),
  searchGridPointDetail: (locationId:number,pointKey:string) => request<Row>(`/utilidades/search-grid/${locationId}/point/${encodeURIComponent(pointKey)}`),
  searchGridCustomPoint: (locationId:number,data:Row) => post<Row>(`/utilidades/search-grid/${locationId}/custom-point`,data),
  searchGridDeleteCustomPoint: (locationId:number,pointKey:string) => request<Row>(`/utilidades/search-grid/${locationId}/custom-point/${encodeURIComponent(pointKey)}`,{method:'DELETE'}),
  searchGridSchedule: (locationId:number,schedule:Row) => post<Row>(`/utilidades/search-grid/${locationId}/schedule`,schedule),
  citationTracker: (locationId:number) => request<Row>(`/utilidades/citation-tracker/${locationId}`),
  citationTrackerRun: (locationId:number) => post<Row>(`/utilidades/citation-tracker/${locationId}/run`,{}),
  citationTrackerMasterNap: (locationId:number,data:Row) => put<Row>(`/utilidades/citation-tracker/${locationId}/master-nap`,data),
  citationTrackerAdd: (locationId:number,data:Row) => post<Row>(`/utilidades/citation-tracker/${locationId}/citations`,data),
  citationTrackerUpdate: (locationId:number,citationId:string,data:Row) => put<Row>(`/utilidades/citation-tracker/${locationId}/citations/${encodeURIComponent(citationId)}`,data),
  citationTrackerDelete: (locationId:number,citationId:string) => del<Row>(`/utilidades/citation-tracker/${locationId}/citations/${encodeURIComponent(citationId)}`),
  citationTrackerRefresh: (locationId:number,citationId:string) => post<Row>(`/utilidades/citation-tracker/${locationId}/citations/${encodeURIComponent(citationId)}/refresh`,{}),
  citationTrackerBuilder: (locationId:number,citationId:string) => post<Row>(`/utilidades/citation-tracker/${locationId}/citations/${encodeURIComponent(citationId)}/builder`,{}),
  citationTrackerResolveDuplicate: (locationId:number,duplicateId:string,data:Row) => post<Row>(`/utilidades/citation-tracker/${locationId}/duplicates/${encodeURIComponent(duplicateId)}/resolve`,data),
  citationTrackerSchedule: (locationId:number,schedule:Row) => post<Row>(`/utilidades/citation-tracker/${locationId}/schedule`,schedule),
  citationBuilder: (locationId:number) => request<Row>(`/utilidades/citation-builder/${locationId}`),
  citationBuilderCampaign: (locationId:number,campaignId:number) => request<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}`),
  citationBuilderCreateCampaign: (locationId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns`,data),
  citationBuilderCampaignStatus: (locationId:number,campaignId:number,data:Row) => put<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/status`,data),
  citationBuilderProfile: (locationId:number,campaignId:number,data:Row) => put<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/profile`,data),
  citationBuilderImportTracker: (locationId:number,campaignId:number) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/import-tracker`,{}),
  citationBuilderImportTrackerDuplicates: (locationId:number,campaignId:number) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/import-tracker-duplicates`,{}),
  citationBuilderAddDirectory: (locationId:number,campaignId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/directories`,data),
  citationBuilderItemStatus: (locationId:number,campaignId:number,itemId:number,data:Row) => put<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/items/${itemId}/status`,data),
  citationBuilderAction: (locationId:number,campaignId:number,itemId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/items/${itemId}/actions`,data),
  citationBuilderResolveAction: (locationId:number,campaignId:number,itemId:number,actionId:string) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/items/${itemId}/actions/${encodeURIComponent(actionId)}/resolve`,{}),
  citationBuilderEvidence: (locationId:number,campaignId:number,itemId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/items/${itemId}/evidence`,data),
  citationBuilderQa: (locationId:number,campaignId:number,itemId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/items/${itemId}/qa`,data),
  citationBuilderAddDuplicate: (locationId:number,campaignId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/duplicates`,data),
  citationBuilderUpdateDuplicate: (locationId:number,campaignId:number,duplicateId:string,data:Row) => put<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/duplicates/${encodeURIComponent(duplicateId)}`,data),
  citationBuilderCredential: (locationId:number,campaignId:number,data:Row) => post<Row>(`/utilidades/citation-builder/${locationId}/campaigns/${campaignId}/credentials`,data),
  citationBuilderRunLab: (locationId:number) => post<Row>(`/utilidades/citation-builder/${locationId}/run-local-lab`,{}),
  gbpAudit: (locationId:number) => request<Row>(`/utilidades/gbp-audit/${locationId}`),
  gbpAuditRun: (locationId:number,periodDays=180) => post<Row>(`/utilidades/gbp-audit/${locationId}/run`,{periodDays}),
  gbpAuditSchedule: (locationId:number,schedule:Row) => post<Row>(`/utilidades/gbp-audit/${locationId}/schedule`,schedule),
  reputationManager: (locationId:number) => request<Row>(`/utilidades/reputation-manager/${locationId}`),
  reputationManagerRun: (locationId:number,periodDays=180) => post<Row>(`/utilidades/reputation-manager/${locationId}/run`,{periodDays}),
  reputationResponseSuggestion: (locationId:number,reviewId:string,tone:string) => post<Row>(`/utilidades/reputation-manager/${locationId}/reviews/${encodeURIComponent(reviewId)}/suggestion`,{tone}),
  reputationRespond: (locationId:number,reviewId:string,data:Row) => post<Row>(`/utilidades/reputation-manager/${locationId}/reviews/${encodeURIComponent(reviewId)}/respond`,data),
  reputationCreateCampaign: (locationId:number,data:Row) => post<Row>(`/utilidades/reputation-manager/${locationId}/campaigns`,data),
  reputationCampaignStatus: (locationId:number,campaignId:number,status:string) => put<Row>(`/utilidades/reputation-manager/${locationId}/campaigns/${campaignId}/status`,{status}),
  reputationFeedback: (locationId:number,data:Row) => put<Row>(`/utilidades/reputation-manager/${locationId}/feedback`,data),
  reputationShowcase: (locationId:number,data:Row) => put<Row>(`/utilidades/reputation-manager/${locationId}/showcase`,data),
  reputationAutomation: (locationId:number,data:Row) => put<Row>(`/utilidades/reputation-manager/${locationId}/automation`,data),
  labCatalog: () => request<Row>('/utilidades/lab/catalog'),
  labStatus: async (locationId?:number) => {
    try {
      return await request<Row>(`/utilidades/lab/status${query({ locationId })}`);
    } catch (cause) {
      const message = cause instanceof Error ? cause.message : '';
      // V5387_UTILIDADES_STATUS_LEGACY_FALLBACK
      // A backend process from before v5.38.7 can still reject query-string integers.
      // Retry without the optional parameter so the backend resolves UTIL-DEMO-001 itself.
      if (locationId && /locationId.*integer/i.test(message)) {
        return request<Row>('/utilidades/lab/status');
      }
      throw cause;
    }
  },
  labRun: (locationId:number, toolCode:string) => post<Row>('/utilidades/lab/run',{ locationId, toolCode }),
  labRunAll: (locationId:number) => post<Row>('/utilidades/lab/run-all',{ locationId }),
  labSelfTest: (locationId:number) => post<Row>('/utilidades/lab/self-test',{ locationId }),
};
