import { Agency, Category, Service, Offer, MarketplaceCategory } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Google Business Profile',
    agenciesCount: 145,
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=600',
    slug: 'gpb-optimization'
  },
  {
    id: 'cat-2',
    name: 'Local Pack Strategy',
    agenciesCount: 89,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600',
    slug: 'local-pack'
  },
  {
    id: 'cat-3',
    name: 'Auditoría SEO Local',
    agenciesCount: 210,
    image: 'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?auto=format&fit=crop&q=80&w=600',
    slug: 'local-audit'
  },
  {
    id: 'cat-4',
    name: 'Link Building Local',
    agenciesCount: 75,
    image: 'https://images.unsplash.com/photo-1432885268628-92b8ed96e699?auto=format&fit=crop&q=80&w=600',
    slug: 'local-links'
  },
  {
    id: 'cat-5',
    name: 'Optimización de Contenido',
    agenciesCount: 115,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=600',
    slug: 'local-content'
  },
  {
    id: 'cat-6',
    name: 'Gestión de Reseñas',
    agenciesCount: 130,
    image: 'https://images.unsplash.com/photo-1521791136368-1a46827d0adb?auto=format&fit=crop&q=80&w=600',
    slug: 'review-management'
  }
];


export const MARKETPLACE_CATEGORIES: MarketplaceCategory[] = [
  {
    id: 'directory-cat-01',
    name: 'Auditoria SEO Local',
    description: 'Diagnostico completo de presencia local, oportunidades, competidores, GBP, NAP, contenido y rendimiento.',
    servicesCount: 7,
    iconName: 'ClipboardCheck',
    keywords: ['auditoria', 'auditoría', 'diagnostico', 'diagnóstico', 'visibilidad', 'presencia local', 'competidores'],
    queryName: 'Auditoria SEO Local',
  },
  {
    id: 'directory-cat-02',
    name: 'Google Business Profile',
    description: 'Optimizacion, gestion y mejora de la ficha de Google para aumentar llamadas, rutas, clics y visibilidad.',
    servicesCount: 11,
    iconName: 'Store',
    keywords: ['google business profile', 'gmb', 'gbp', 'ficha de google', 'perfil de empresa', 'llamadas', 'rutas'],
    queryName: 'Google Business Profile',
  },
  {
    id: 'directory-cat-03',
    name: 'Local Pack y Ranking',
    description: 'Posicionamiento en Google Maps, Local Pack, competencia geografica y rankings por zona.',
    servicesCount: 9,
    iconName: 'MapPin',
    keywords: ['local pack', 'ranking', 'mapas', 'google maps', 'posicionamiento', 'competencia geografica', 'competencia geográfica'],
    queryName: 'Local Pack Ranking',
  },
  {
    id: 'directory-cat-04',
    name: 'Link Building Local',
    description: 'Autoridad local mediante enlaces, menciones, relaciones publicas locales y senales NAP.',
    servicesCount: 7,
    iconName: 'Link2',
    keywords: ['link building', 'enlaces', 'autoridad', 'backlinks', 'menciones', 'relaciones publicas', 'relaciones públicas'],
    queryName: 'Link Building Local',
  },
  {
    id: 'directory-cat-05',
    name: 'SEO Tecnico Local',
    description: 'Rastreo, indexacion, velocidad, seguridad, arquitectura local y correccion tecnica.',
    servicesCount: 7,
    iconName: 'Code2',
    keywords: ['seo tecnico', 'seo técnico', 'indexacion', 'indexación', 'rastreo', 'velocidad', 'seguridad', 'arquitectura local'],
    queryName: 'SEO Tecnico Local',
  },
  {
    id: 'directory-cat-06',
    name: 'SEO On-Page Local',
    description: 'Optimizacion de titulos, metadatos, estructura, landings, contenido y conversion local.',
    servicesCount: 8,
    iconName: 'FileText',
    keywords: ['on page', 'on-page', 'contenido', 'keywords', 'landings locales', 'metadatos', 'conversion local', 'conversión local'],
    queryName: 'SEO On Page Local',
  },
  {
    id: 'directory-cat-07',
    name: 'Reputacion y Resenas',
    description: 'Gestion de confianza, generacion de resenas, respuestas, monitoreo y reputacion online.',
    servicesCount: 6,
    iconName: 'MessageSquareQuote',
    keywords: ['reputacion', 'reputación', 'resenas', 'reseñas', 'opiniones', 'confianza', 'respuesta a resenas', 'respuesta a reseñas'],
    queryName: 'Reputacion Resenas',
  },
  {
    id: 'directory-cat-08',
    name: 'Citaciones y NAP',
    description: 'Consistencia de nombre, direccion y telefono, directorios, duplicados y autoridad de citaciones.',
    servicesCount: 5,
    iconName: 'Building2',
    keywords: ['citaciones', 'nap', 'directorios', 'duplicados', 'nombre direccion telefono', 'nombre dirección teléfono'],
    queryName: 'Citaciones NAP',
  },
  {
    id: 'directory-cat-09',
    name: 'Reportes y Analytics',
    description: 'Medicion de resultados, dashboards, conversiones, ranking, GBP y analitica local.',
    servicesCount: 7,
    iconName: 'BarChart3',
    keywords: ['reportes', 'analytics', 'analitica', 'analítica', 'kpi', 'dashboard', 'medicion', 'medición', 'conversiones'],
    queryName: 'Reportes Analytics',
  },
  {
    id: 'directory-cat-10',
    name: 'Mapas de Calor Local',
    description: 'Mapas de calor de ranking local por zonas, cobertura Top 3 y oportunidades territoriales.',
    servicesCount: 5,
    iconName: 'Target',
    keywords: ['mapas de calor', 'ranking grid', 'local pack', 'posiciones', 'top 3', 'competencia', 'zonas'],
    queryName: 'Mapas Calor Local',
  },
  {
    id: 'directory-cat-11',
    name: 'Alternativas Locales',
    description: 'Presencia en buscadores alternativos, directorios verticales, Apple Maps, Bing Places y ecosistemas fuera de Google.',
    servicesCount: 5,
    iconName: 'GitBranch',
    keywords: ['alternativas locales', 'bing places', 'apple maps', 'directorios verticales', 'buscadores alternativos'],
    queryName: 'Alternativas Locales',
  },
  {
    id: 'directory-cat-12',
    name: 'Contenido Local',
    description: 'Contenido geografico, blog local, posts GBP, FAQ, landings y calendario editorial.',
    servicesCount: 11,
    iconName: 'Pencil',
    keywords: ['contenido local', 'blog local', 'posts gbp', 'guias locales', 'guías locales', 'faq', 'calendario editorial'],
    queryName: 'Contenido Local',
  },
  {
    id: 'directory-cat-13',
    name: 'Schema Local',
    description: 'Datos estructurados LocalBusiness, FAQ, productos, servicios y marcado tecnico para buscadores.',
    servicesCount: 4,
    iconName: 'Workflow',
    keywords: ['schema', 'schema local', 'datos estructurados', 'json ld', 'rich results', 'localbusiness', 'faq'],
    queryName: 'Schema Local',
  },
  {
    id: 'directory-cat-14',
    name: 'Software y Automatizacion',
    description: 'Herramientas, dashboards, tracking, automatizacion y plataformas de monitoreo SEO local.',
    servicesCount: 5,
    iconName: 'TerminalSquare',
    keywords: ['software', 'herramientas', 'automatizacion', 'automatización', 'dashboard', 'tracking', 'monitoreo'],
    queryName: 'Software Automatizacion',
  },
  {
    id: 'directory-cat-15',
    name: 'Consultoria y Estrategia',
    description: 'Diagnostico experto, estrategia personalizada, mentorias, planes de accion y revision ejecutiva.',
    servicesCount: 10,
    iconName: 'Headphones',
    keywords: ['consultoria', 'consultoría', 'estrategia', 'asesoramiento', 'mentoria', 'mentoría', 'plan de accion', 'plan de acción'],
    queryName: 'Consultoria Estrategia',
  },
  {
    id: 'directory-cat-16',
    name: 'SEO Local para E-commerce',
    description: 'SEO local para tiendas online, categorias, fichas de producto, landings locales y contenido comercial.',
    servicesCount: 11,
    iconName: 'ShoppingCart',
    keywords: ['seo local ecommerce', 'seo local e-commerce', 'tiendas online', 'categorias ecommerce', 'categorías ecommerce', 'fichas de producto', 'landings locales'],
    queryName: 'SEO Local Ecommerce',
  },
];

export const AGENCIES: Agency[] = [
  {
    id: 'agency-1',
    slug: 'visibilidad-pro-seo',
    name: 'Visibilidad Pro SEO',
    logoLetter: 'V',
    logoBgColor: 'bg-[#D32323]',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=900',
    rating: 4.9,
    reviewsCount: 356,
    highlightReview: 'Incrementaron nuestro tráfico orgánico local un 240% en solo 3 meses de trabajo constante.',
    commercialSummary: 'Especialistas en auditorías locales, GBP y paquetes de posicionamiento para negocios con múltiples sedes.',
    caseStudy: 'Restaurante local pasó de 18 a 72 llamadas mensuales desde Google Maps.',
    priceLevel: '$$',
    startingPrice: 450,
    budgetMin: 450,
    budgetMax: 4000,
    services: ['Google Business Profile', 'Local Pack Strategy', 'Auditoría SEO Local', 'Presencial'],
    speciality: 'Auditoría SEO Local',
    location: 'Bogotá, Colombia',
    city: 'Bogotá',
    country: 'CO',
    coords: { x: 32, y: 38 },
    distance: 1.5,
    employeesRange: '25+ empleados',
    experienceYears: 8,
    languages: ['Español'],
    workModes: ['Presencial', 'Remota'],
    certificationLevel: 'Destacada',
    badgeLabel: 'Destacado',
    recommended: true,
    responseTimeHours: 4,
    qualifiedProjects: 86,
    trustScore: 96,
    successRate: 92,
    audited: true,
    profileCompleteness: 98,
    isVerified: true,
    isTopRated: true,
    phone: '+57 601 555 0101',
    email: 'contacto@visibilidadproseo.example'
  },
  {
    id: 'agency-2',
    slug: 'mapa-ranking-agency',
    name: 'Mapa & Ranking Agency',
    logoLetter: 'M',
    logoBgColor: 'bg-[#0074E0]',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=900',
    rating: 4.8,
    reviewsCount: 248,
    highlightReview: 'Excelentes profesionales, nos ayudaron con el SEO técnico de nuestra red de tiendas físicas.',
    commercialSummary: 'Equipo de Local Pack, geogrids y optimización técnica para cadenas regionales.',
    caseStudy: 'Cadena retail aumentó 31% las solicitudes de ruta en 60 días.',
    priceLevel: '$$',
    startingPrice: 380,
    budgetMin: 380,
    budgetMax: 3000,
    services: ['Local Pack Strategy', 'Optimización de Contenido', 'Auditoría SEO Local', 'Híbrida'],
    speciality: 'Local Pack Strategy',
    location: 'Medellín, Colombia',
    city: 'Medellín',
    country: 'CO',
    coords: { x: 45, y: 46 },
    distance: 2.1,
    employeesRange: '15-20 empleados',
    experienceYears: 6,
    languages: ['Español', 'Inglés'],
    workModes: ['Híbrida', 'Remota'],
    certificationLevel: 'Destacada',
    badgeLabel: 'Destacado',
    recommended: true,
    responseTimeHours: 6,
    qualifiedProjects: 74,
    trustScore: 94,
    successRate: 89,
    audited: true,
    profileCompleteness: 96,
    isVerified: true,
    isTopRated: true,
    phone: '+57 604 555 0102',
    email: 'hola@maparanking.example'
  },
  {
    id: 'agency-3',
    slug: 'impulsa-local-studio',
    name: 'Impulsa Local Studio',
    logoLetter: 'I',
    logoBgColor: 'bg-[#0D9488]',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=900',
    rating: 4.7,
    reviewsCount: 189,
    highlightReview: 'La mejor relación calidad-precio para auditorías y optimizaciones completas de Google Business Profile.',
    commercialSummary: 'Studio boutique para GBP, reseñas, auditorías y contenidos locales de rápida implementación.',
    caseStudy: 'Clínica local duplicó solicitudes de WhatsApp con optimización de perfil y reseñas.',
    priceLevel: '$',
    startingPrice: 290,
    budgetMin: 290,
    budgetMax: 1800,
    services: ['Google Business Profile', 'Auditoría SEO Local', 'Gestión de Reseñas', 'Remota'],
    speciality: 'Google Business Profile',
    location: 'Cali, Colombia',
    city: 'Cali',
    country: 'CO',
    coords: { x: 60, y: 55 },
    distance: 3.4,
    employeesRange: '10-15 empleados',
    experienceYears: 5,
    languages: ['Español'],
    workModes: ['Remota', 'Híbrida'],
    certificationLevel: 'Destacada',
    badgeLabel: 'Destacado',
    recommended: false,
    responseTimeHours: 8,
    qualifiedProjects: 52,
    trustScore: 90,
    successRate: 86,
    audited: true,
    profileCompleteness: 94,
    isVerified: true,
    isTopRated: false,
    phone: '+57 602 555 0103',
    email: 'ventas@impulsalocal.example'
  },
  {
    id: 'agency-4',
    slug: 'local-rankers',
    name: 'Local Rankers',
    logoLetter: 'L',
    logoBgColor: 'bg-[#111827]',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=900',
    rating: 4.6,
    reviewsCount: 142,
    highlightReview: 'Especialistas absolutos en dominar NAP, mapas, reseñas y presencia hiperlocal.',
    commercialSummary: 'Equipo enfocado en NAP, citaciones, link building local y reputación para mercados competidos.',
    caseStudy: 'Empresa de servicios subió 19 posiciones promedio en búsquedas de barrio.',
    priceLevel: '$$',
    startingPrice: 320,
    budgetMin: 320,
    budgetMax: 2400,
    services: ['Link Building Local', 'Google Business Profile', 'Gestión de Reseñas', 'Híbrida'],
    speciality: 'Link Building Local',
    location: 'Barranquilla, Colombia',
    city: 'Barranquilla',
    country: 'CO',
    coords: { x: 25, y: 62 },
    distance: 4.8,
    employeesRange: '8-10 empleados',
    experienceYears: 4,
    languages: ['Español'],
    workModes: ['Híbrida'],
    certificationLevel: 'Recomendada',
    badgeLabel: 'Recomendado',
    recommended: true,
    responseTimeHours: 12,
    qualifiedProjects: 41,
    trustScore: 88,
    successRate: 83,
    audited: true,
    profileCompleteness: 91,
    isVerified: true,
    isTopRated: false,
    phone: '+57 605 555 0104',
    email: 'rankers@localrankers.example'
  },
  {
    id: 'agency-5',
    slug: 'seo-certero',
    name: 'SEO Certero',
    logoLetter: 'S',
    logoBgColor: 'bg-[#EC4899]',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=900',
    rating: 4.6,
    reviewsCount: 98,
    highlightReview: 'Atención personalizada, informes súper claros y excelente soporte y subida de posiciones.',
    commercialSummary: 'Consultoría remota para auditorías SEO local, contenido y seguimiento semanal.',
    caseStudy: 'Profesional local pasó de 11 a 4 palabras clave en Top 3 local.',
    priceLevel: '$',
    startingPrice: 240,
    budgetMin: 240,
    budgetMax: 1500,
    services: ['Auditoría SEO Local', 'Optimización de Contenido', 'Link Building Local', 'Remota'],
    speciality: 'Optimización de Contenido',
    location: 'Pereira, Colombia',
    city: 'Pereira',
    country: 'CO',
    coords: { x: 52, y: 64 },
    distance: 5.2,
    employeesRange: '5-10 empleados',
    experienceYears: 4,
    languages: ['Español'],
    workModes: ['Remota'],
    certificationLevel: 'Recomendada',
    badgeLabel: 'Recomendado',
    recommended: true,
    responseTimeHours: 10,
    qualifiedProjects: 37,
    trustScore: 86,
    successRate: 81,
    audited: true,
    profileCompleteness: 90,
    isVerified: true,
    isTopRated: false,
    phone: '+57 606 555 0105',
    email: 'proyectos@seocertero.example'
  },
  {
    id: 'agency-6',
    slug: 'estrategia-local',
    name: 'Estrategia Local',
    logoLetter: 'E',
    logoBgColor: 'bg-[#10B981]',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=80&w=900',
    rating: 4.5,
    reviewsCount: 87,
    highlightReview: 'Rápida respuesta y automatización inteligente de citaciones locales para PYMEs.',
    commercialSummary: 'Gestión local combinada de GBP, reportes, automatización y contenido base.',
    caseStudy: 'Negocio de mantenimiento aumentó 42% formularios desde páginas locales.',
    priceLevel: '$$',
    startingPrice: 420,
    budgetMin: 420,
    budgetMax: 2600,
    services: ['Google Business Profile', 'Link Building Local', 'Analítica y Reportes', 'Presencial'],
    speciality: 'Reportes y Analytics',
    location: 'Bucaramanga, Colombia',
    city: 'Bucaramanga',
    country: 'CO',
    coords: { x: 71, y: 34 },
    distance: 6.7,
    employeesRange: '8-12 empleados',
    experienceYears: 3,
    languages: ['Español'],
    workModes: ['Presencial', 'Híbrida'],
    certificationLevel: 'Estándar',
    badgeLabel: 'Estándar',
    recommended: false,
    responseTimeHours: 16,
    qualifiedProjects: 29,
    trustScore: 82,
    successRate: 78,
    audited: true,
    profileCompleteness: 87,
    isVerified: true,
    isTopRated: false,
    phone: '+57 607 555 0106',
    email: 'info@estrategialocal.example'
  },
  {
    id: 'agency-7',
    slug: 'seo-local-colombia',
    name: 'SEO Local Colombia',
    logoLetter: 'S',
    logoBgColor: 'bg-[#6366F1]',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=900',
    rating: 4.7,
    reviewsCount: 112,
    highlightReview: 'La mejor opción para optimizar fichas múltiples en toda Colombia. Logramos auditorías consistentes y accionables.',
    commercialSummary: 'Agencia regional para cadenas con varias ubicaciones, citaciones y contenido por ciudad.',
    caseStudy: 'Franquicia con 12 sedes normalizó NAP y subió cobertura Top 10 al 71%.',
    priceLevel: '$$',
    startingPrice: 340,
    budgetMin: 340,
    budgetMax: 2800,
    services: ['Google Business Profile', 'Citas y NAP', 'SEO Técnico Local', 'Remota'],
    speciality: 'Citaciones y NAP',
    location: 'Bogotá, Colombia',
    city: 'Bogotá',
    country: 'CO',
    coords: { x: 38, y: 48 },
    distance: 2.3,
    employeesRange: '10-15 empleados',
    experienceYears: 5,
    languages: ['Español'],
    workModes: ['Remota', 'Híbrida'],
    certificationLevel: 'Recomendada',
    badgeLabel: 'Recomendado',
    recommended: true,
    responseTimeHours: 8,
    qualifiedProjects: 55,
    trustScore: 89,
    successRate: 84,
    audited: true,
    profileCompleteness: 92,
    isVerified: true,
    isTopRated: false,
    phone: '+57 601 555 0107',
    email: 'contacto@seolocalcolombia.example'
  },
  {
    id: 'agency-8',
    slug: 'santander-local-rank',
    name: 'Santander Local Rank',
    logoLetter: 'S',
    logoBgColor: 'bg-[#2563EB]',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=900',
    rating: 4.6,
    reviewsCount: 78,
    highlightReview: 'Recomiendo 100% su servicio de Link Building Local y optimización de NAP.',
    commercialSummary: 'Especialistas regionales en enlaces locales, directorios, contenido y reseñas.',
    caseStudy: 'Constructor local mejoró autoridad de páginas de servicio en 46 días.',
    priceLevel: '$',
    startingPrice: 310,
    budgetMin: 310,
    budgetMax: 1700,
    services: ['Link Building Local', 'Citas y NAP', 'Local Pack Strategy', 'Híbrida'],
    speciality: 'Link Building Local',
    location: 'Bucaramanga, Colombia',
    city: 'Bucaramanga',
    country: 'CO',
    coords: { x: 68, y: 42 },
    distance: 3.8,
    employeesRange: '5-10 empleados',
    experienceYears: 4,
    languages: ['Español'],
    workModes: ['Híbrida', 'Remota'],
    certificationLevel: 'Recomendada',
    badgeLabel: 'Recomendado',
    recommended: true,
    responseTimeHours: 12,
    qualifiedProjects: 33,
    trustScore: 85,
    successRate: 80,
    audited: true,
    profileCompleteness: 89,
    isVerified: true,
    isTopRated: false,
    phone: '+57 607 555 0108',
    email: 'rank@santanderlocal.example'
  },
  {
    id: 'agency-9',
    slug: 'eje-cafetero-posicionamiento',
    name: 'Eje Cafetero Posicionamiento',
    logoLetter: 'E',
    logoBgColor: 'bg-[#059669]',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=900',
    rating: 4.8,
    reviewsCount: 135,
    highlightReview: 'Llevaron nuestras tiendas de café a la primera posición para búsquedas locales en menos de tres meses.',
    commercialSummary: 'Posicionamiento local para turismo, retail y negocios de alto tráfico físico.',
    caseStudy: 'Marca turística logró 2.8x crecimiento en solicitudes de ruta desde Maps.',
    priceLevel: '$$',
    startingPrice: 400,
    budgetMin: 400,
    budgetMax: 3200,
    services: ['Google Business Profile', 'Local Pack Strategy', 'Optimización de Contenido', 'Presencial'],
    speciality: 'Local Pack Strategy',
    location: 'Pereira, Colombia',
    city: 'Pereira',
    country: 'CO',
    coords: { x: 57, y: 70 },
    distance: 1.9,
    employeesRange: '15-20 empleados',
    experienceYears: 7,
    languages: ['Español'],
    workModes: ['Presencial', 'Híbrida'],
    certificationLevel: 'Destacada',
    badgeLabel: 'Destacado',
    recommended: false,
    responseTimeHours: 5,
    qualifiedProjects: 62,
    trustScore: 93,
    successRate: 88,
    audited: true,
    profileCompleteness: 95,
    isVerified: true,
    isTopRated: true,
    phone: '+57 606 555 0109',
    email: 'hola@ejecafeteroseo.example'
  }
];

export const POPULAR_SERVICES: Service[] = [
  {
    id: "fur-s-gbp-001",
    title: "Optimización Completa de GBP",
    iconName: "Store",
    description: "Optimización integral de la ficha para máxima visibilidad y llamadas.",
    price: 99,
    isPopular: true,
    code: "FUR-S-GBP-001",
    furNumber: 1,
    sourceCategoryName: "Google Business Profile (GBP)",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-gbp-002",
    title: "Gestión de Publicaciones en GBP",
    iconName: "Newspaper",
    description: "Publicaciones semanales para atraer y mantener clientes.",
    price: 49,
    isPopular: false,
    code: "FUR-S-GBP-002",
    furNumber: 2,
    sourceCategoryName: "Google Business Profile (GBP)",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-gbp-003",
    title: "Gestión de Reseñas y Reputación",
    iconName: "MessageSquareQuote",
    description: "Estrategia para obtener más reseñas y mejorar tu reputación online.",
    price: 79,
    isPopular: true,
    code: "FUR-S-GBP-003",
    furNumber: 3,
    sourceCategoryName: "Google Business Profile (GBP)",
    categoryId: "directory-cat-07",
    categoryName: "Reputación y Reseñas",
    categorySlug: "reputacion-y-resenas",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-gbp-004",
    title: "Optimización de Fotos y Videos en GBP",
    iconName: "Image",
    description: "Mejora tu galería para generar más confianza y clics.",
    price: 39,
    isPopular: false,
    code: "FUR-S-GBP-004",
    furNumber: 4,
    sourceCategoryName: "Google Business Profile (GBP)",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-gbp-005",
    title: "Auditoría de Google Business Profile",
    iconName: "ClipboardCheck",
    description: "Análisis completo de tu GBP con plan de mejoras prioritarias.",
    price: 69,
    isPopular: true,
    code: "FUR-S-GBP-005",
    furNumber: 5,
    sourceCategoryName: "Google Business Profile (GBP)",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 3,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lp-001",
    title: "SEO Local para Local Pack (Mensual)",
    iconName: "MapPin",
    description: "Estrategias mensuales para mejorar tu posición en el Local Pack.",
    price: 149,
    isPopular: true,
    code: "FUR-S-LP-001",
    furNumber: 6,
    sourceCategoryName: "Posicionamiento Local (Local Pack)",
    categoryId: "directory-cat-03",
    categoryName: "Local Pack y Ranking",
    categorySlug: "local-pack-y-ranking",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lp-002",
    title: "Optimización de Citaciones Locales",
    iconName: "Building2",
    description: "Creación y limpieza de citas en directorios locales relevantes.",
    price: 99,
    isPopular: false,
    code: "FUR-S-LP-002",
    furNumber: 7,
    sourceCategoryName: "Posicionamiento Local (Local Pack)",
    categoryId: "directory-cat-08",
    categoryName: "Citaciones y NAP",
    categorySlug: "citaciones-y-nap",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 14,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lp-003",
    title: "Auditoría de SEO Local",
    iconName: "SearchCheck",
    description: "Análisis completo de tu presencia local y oportunidades.",
    price: 129,
    isPopular: true,
    code: "FUR-S-LP-003",
    furNumber: 8,
    sourceCategoryName: "Posicionamiento Local (Local Pack)",
    categoryId: "directory-cat-01",
    categoryName: "Auditoría SEO Local",
    categorySlug: "auditoria-seo-local",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lp-004",
    title: "Competitor Local Analysis",
    iconName: "UsersRound",
    description: "Estudio de competidores locales y estrategias para superarlos.",
    price: 89,
    isPopular: false,
    code: "FUR-S-LP-004",
    furNumber: 9,
    sourceCategoryName: "Posicionamiento Local (Local Pack)",
    categoryId: "directory-cat-03",
    categoryName: "Local Pack y Ranking",
    categorySlug: "local-pack-y-ranking",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lp-005",
    title: "Estrategia Local Pack Personalizada",
    iconName: "Target",
    description: "Plan estratégico 100% personalizado para dominar tu zona.",
    price: 199,
    isPopular: true,
    code: "FUR-S-LP-005",
    furNumber: 10,
    sourceCategoryName: "Posicionamiento Local (Local Pack)",
    categoryId: "directory-cat-03",
    categoryName: "Local Pack y Ranking",
    categorySlug: "local-pack-y-ranking",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 10,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lb-001",
    title: "Backlinks Locales (Básico)",
    iconName: "Link2",
    description: "10 enlaces locales de calidad y relevancia básica.",
    price: 99,
    isPopular: false,
    code: "FUR-S-LB-001",
    furNumber: 11,
    sourceCategoryName: "Link Building Local",
    categoryId: "directory-cat-04",
    categoryName: "Link Building Local",
    categorySlug: "link-building-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 10,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lb-002",
    title: "Backlinks Locales (Estándar)",
    iconName: "Link2",
    description: "25 enlaces locales de alta autoridad y relevancia.",
    price: 199,
    isPopular: true,
    code: "FUR-S-LB-002",
    furNumber: 12,
    sourceCategoryName: "Link Building Local",
    categoryId: "directory-cat-04",
    categoryName: "Link Building Local",
    categorySlug: "link-building-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 20,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lb-003",
    title: "Backlinks Locales (Premium)",
    iconName: "ShieldCheck",
    description: "50 enlaces locales premium para máxima autoridad.",
    price: 299,
    isPopular: true,
    code: "FUR-S-LB-003",
    furNumber: 13,
    sourceCategoryName: "Link Building Local",
    categoryId: "directory-cat-04",
    categoryName: "Link Building Local",
    categorySlug: "link-building-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lb-004",
    title: "Construcción de Enlaces NAP",
    iconName: "Building2",
    description: "Enlaces consistentes con tu NAP en directorios clave.",
    price: 79,
    isPopular: false,
    code: "FUR-S-LB-004",
    furNumber: 14,
    sourceCategoryName: "Link Building Local",
    categoryId: "directory-cat-04",
    categoryName: "Link Building Local",
    categorySlug: "link-building-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 10,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-lb-005",
    title: "Outreach y PR Local",
    iconName: "Megaphone",
    description: "Campañas de outreach para conseguir menciones y enlaces.",
    price: 249,
    isPopular: true,
    code: "FUR-S-LB-005",
    furNumber: 15,
    sourceCategoryName: "Link Building Local",
    categoryId: "directory-cat-04",
    categoryName: "Link Building Local",
    categorySlug: "link-building-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-st-001",
    title: "Auditoría Técnica SEO Local",
    iconName: "Code2",
    description: "Análisis técnico completo de tu sitio con reporte y soluciones.",
    price: 149,
    isPopular: true,
    code: "FUR-S-ST-001",
    furNumber: 16,
    sourceCategoryName: "SEO Técnico Local",
    categoryId: "directory-cat-05",
    categoryName: "SEO Técnico Local",
    categorySlug: "seo-tecnico-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-st-002",
    title: "Optimización de Velocidad",
    iconName: "Gauge",
    description: "Mejora la velocidad de carga para mejor experiencia y rankings.",
    price: 99,
    isPopular: false,
    code: "FUR-S-ST-002",
    furNumber: 17,
    sourceCategoryName: "SEO Técnico Local",
    categoryId: "directory-cat-05",
    categoryName: "SEO Técnico Local",
    categorySlug: "seo-tecnico-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-st-003",
    title: "SEO On-Page Técnico",
    iconName: "FileText",
    description: "Optimización de títulos, meta, headers, schema y más.",
    price: 129,
    isPopular: false,
    code: "FUR-S-ST-003",
    furNumber: 18,
    sourceCategoryName: "SEO Técnico Local",
    categoryId: "directory-cat-06",
    categoryName: "SEO On-Page Local",
    categorySlug: "seo-on-page-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-st-004",
    title: "Implementación de Schema Local",
    iconName: "Workflow",
    description: "Datos estructurados LocalBusiness para mejores resultados.",
    price: 79,
    isPopular: false,
    code: "FUR-S-ST-004",
    furNumber: 19,
    sourceCategoryName: "SEO Técnico Local",
    categoryId: "directory-cat-13",
    categoryName: "Schema",
    categorySlug: "schema",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-st-005",
    title: "Corrección de Errores Técnicos",
    iconName: "Wrench",
    description: "Solución de errores de rastreo, indexación y problemas técnicos.",
    price: 99,
    isPopular: false,
    code: "FUR-S-ST-005",
    furNumber: 20,
    sourceCategoryName: "SEO Técnico Local",
    categoryId: "directory-cat-05",
    categoryName: "SEO Técnico Local",
    categorySlug: "seo-tecnico-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ct-001",
    title: "Redacción de Contenido Local (1 página)",
    iconName: "FileText",
    description: "Contenido optimizado para atraer tráfico local y clientes.",
    price: 49,
    isPopular: false,
    code: "FUR-S-CT-001",
    furNumber: 21,
    sourceCategoryName: "Contenido Local",
    categoryId: "directory-cat-12",
    categoryName: "Contenido Local",
    categorySlug: "contenido-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ct-002",
    title: "Blog Local Mensual",
    iconName: "Newspaper",
    description: "4 artículos mensuales optimizados para SEO local.",
    price: 119,
    isPopular: true,
    code: "FUR-S-CT-002",
    furNumber: 22,
    sourceCategoryName: "Contenido Local",
    categoryId: "directory-cat-12",
    categoryName: "Contenido Local",
    categorySlug: "contenido-local",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ct-003",
    title: "Páginas de Servicio Optimizadas",
    iconName: "PanelTop",
    description: "Páginas de servicio optimizadas para conversiones y SEO.",
    price: 79,
    isPopular: false,
    code: "FUR-S-CT-003",
    furNumber: 23,
    sourceCategoryName: "Contenido Local",
    categoryId: "directory-cat-12",
    categoryName: "Contenido Local",
    categorySlug: "contenido-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ct-004",
    title: "Landing Page Local",
    iconName: "LayoutTemplate",
    description: "Diseño y redacción de landing page para campañas locales.",
    price: 129,
    isPopular: true,
    code: "FUR-S-CT-004",
    furNumber: 24,
    sourceCategoryName: "Contenido Local",
    categoryId: "directory-cat-12",
    categoryName: "Contenido Local",
    categorySlug: "contenido-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 10,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ct-005",
    title: "Preguntas Frecuentes (FAQ) Local",
    iconName: "CircleHelp",
    description: "Sección FAQ optimizada para tu sitio y tu GBP.",
    price: 49,
    isPopular: false,
    code: "FUR-S-CT-005",
    furNumber: 25,
    sourceCategoryName: "Contenido Local",
    categoryId: "directory-cat-12",
    categoryName: "Contenido Local",
    categorySlug: "contenido-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 3,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-an-001",
    title: "Mapas de Calor (Básico)",
    iconName: "Map",
    description: "Análisis de comportamiento básico con heatmaps.",
    price: 79,
    isPopular: false,
    code: "FUR-S-AN-001",
    furNumber: 26,
    sourceCategoryName: "Analítica y Mapas de Calor",
    categoryId: "directory-cat-10",
    categoryName: "Mapas de Calor Local",
    categorySlug: "mapas-calor-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-an-002",
    title: "Mapas de Calor (Avanzado)",
    iconName: "MapPinned",
    description: "Análisis avanzado con grabaciones de sesiones.",
    price: 149,
    isPopular: true,
    code: "FUR-S-AN-002",
    furNumber: 27,
    sourceCategoryName: "Analítica y Mapas de Calor",
    categoryId: "directory-cat-10",
    categoryName: "Mapas de Calor Local",
    categorySlug: "mapas-calor-local",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-an-003",
    title: "Análisis de Conversiones",
    iconName: "ChartNoAxesCombined",
    description: "Configuración y análisis de conversiones y eventos clave.",
    price: 99,
    isPopular: false,
    code: "FUR-S-AN-003",
    furNumber: 28,
    sourceCategoryName: "Analítica y Mapas de Calor",
    categoryId: "directory-cat-09",
    categoryName: "Reportes y Analytics",
    categorySlug: "reportes-y-analytics",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-an-004",
    title: "Informe Analítico Mensual",
    iconName: "FileBarChart",
    description: "Reporte mensual de tráfico, usuarios y comportamiento.",
    price: 89,
    isPopular: false,
    code: "FUR-S-AN-004",
    furNumber: 29,
    sourceCategoryName: "Analítica y Mapas de Calor",
    categoryId: "directory-cat-09",
    categoryName: "Reportes y Analytics",
    categorySlug: "reportes-y-analytics",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-an-005",
    title: "Dashboard Personalizado",
    iconName: "BarChart3",
    description: "Dashboard de medida con tus KPIs más importantes.",
    price: 129,
    isPopular: true,
    code: "FUR-S-AN-005",
    furNumber: 30,
    sourceCategoryName: "Analítica y Mapas de Calor",
    categoryId: "directory-cat-09",
    categoryName: "Reportes y Analytics",
    categorySlug: "reportes-y-analytics",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-pb-001",
    title: "Publicaciones en GBP (Mensual)",
    iconName: "Newspaper",
    description: "Publicaciones semanales en Google Business Profile.",
    price: 49,
    isPopular: false,
    code: "FUR-S-PB-001",
    furNumber: 31,
    sourceCategoryName: "Publicaciones y Gestión de GBP",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-pb-002",
    title: "Gestión Completa de GBP",
    iconName: "BriefcaseBusiness",
    description: "Gestión integral de publicaciones, fotos, reseñas y más.",
    price: 149,
    isPopular: true,
    code: "FUR-S-PB-002",
    furNumber: 32,
    sourceCategoryName: "Publicaciones y Gestión de GBP",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-pb-003",
    title: "Publicaciones con Diseño",
    iconName: "Palette",
    description: "Publicaciones diseñadas para mayor impacto y engagement.",
    price: 79,
    isPopular: false,
    code: "FUR-S-PB-003",
    furNumber: 33,
    sourceCategoryName: "Publicaciones y Gestión de GBP",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-pb-004",
    title: "Publicaciones de Ofertas y Eventos",
    iconName: "BadgePercent",
    description: "Promoción de ofertas y eventos para aumentar visitas y clics.",
    price: 59,
    isPopular: false,
    code: "FUR-S-PB-004",
    furNumber: 34,
    sourceCategoryName: "Publicaciones y Gestión de GBP",
    categoryId: "directory-cat-02",
    categoryName: "Google Business Profile",
    categorySlug: "google-business-profile",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-pb-005",
    title: "Calendario Editorial Local",
    iconName: "CalendarDays",
    description: "Planificación de contenido y publicaciones para todo el mes.",
    price: 99,
    isPopular: false,
    code: "FUR-S-PB-005",
    furNumber: 35,
    sourceCategoryName: "Publicaciones y Gestión de GBP",
    categoryId: "directory-cat-12",
    categoryName: "Contenido Local",
    categorySlug: "contenido-local",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ec-001",
    title: "SEO Local para E-commerce",
    iconName: "ShoppingCart",
    description: "Optimización de tienda online para búsquedas locales.",
    price: 149,
    isPopular: true,
    code: "FUR-S-EC-001",
    furNumber: 41,
    sourceCategoryName: "Multi-Ubicaciones / E-commerce Local",
    categoryId: "directory-cat-16",
    categoryName: "SEO Local para E-commerce",
    categorySlug: "seo-local-ecommerce",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ec-002",
    title: "Páginas de Categoría Optimizadas",
    iconName: "PanelsTopLeft",
    description: "Optimización de categorías para mejor visibilidad.",
    price: 99,
    isPopular: false,
    code: "FUR-S-EC-002",
    furNumber: 42,
    sourceCategoryName: "Multi-Ubicaciones / E-commerce Local",
    categoryId: "directory-cat-16",
    categoryName: "SEO Local para E-commerce",
    categorySlug: "seo-local-ecommerce",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 7,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ec-003",
    title: "Optimización de Fichas de Producto",
    iconName: "PackageCheck",
    description: "Fichas de productos de rendimiento SEO y ubicación.",
    price: 79,
    isPopular: false,
    code: "FUR-S-EC-003",
    furNumber: 43,
    sourceCategoryName: "Multi-Ubicaciones / E-commerce Local",
    categoryId: "directory-cat-16",
    categoryName: "SEO Local para E-commerce",
    categorySlug: "seo-local-ecommerce",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ec-004",
    title: "SEO Técnico para E-commerce",
    iconName: "Code2",
    description: "Mejora técnica para e-commerce: indexación, velocidad y más.",
    price: 149,
    isPopular: true,
    code: "FUR-S-EC-004",
    furNumber: 44,
    sourceCategoryName: "Multi-Ubicaciones / E-commerce Local",
    categoryId: "directory-cat-16",
    categoryName: "SEO Local para E-commerce",
    categorySlug: "seo-local-ecommerce",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 10,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ec-005",
    title: "Estrategia de Contenido para E-commerce",
    iconName: "FileText",
    description: "Plan de contenido para atraer tráfico local a tu tienda online.",
    price: 129,
    isPopular: false,
    code: "FUR-S-EC-005",
    furNumber: 45,
    sourceCategoryName: "Multi-Ubicaciones / E-commerce Local",
    categoryId: "directory-cat-16",
    categoryName: "SEO Local para E-commerce",
    categorySlug: "seo-local-ecommerce",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ce-001",
    title: "Consultoría SEO Local (1 hora)",
    iconName: "Headphones",
    description: "Sesión de consultoría personalizada con experto SEO local.",
    price: 79,
    isPopular: false,
    code: "FUR-S-CE-001",
    furNumber: 46,
    sourceCategoryName: "Consultoría y Estrategia",
    categoryId: "directory-cat-15",
    categoryName: "Consultoría",
    categorySlug: "consultoria",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 1,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ce-002",
    title: "Estrategia SEO Local Personalizada",
    iconName: "Target",
    description: "Plan estratégico a medida para tu negocio y objetivos.",
    price: 99,
    isPopular: true,
    code: "FUR-S-CE-002",
    furNumber: 47,
    sourceCategoryName: "Consultoría y Estrategia",
    categoryId: "directory-cat-15",
    categoryName: "Consultoría",
    categorySlug: "consultoria",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ce-003",
    title: "Mentoría SEO Local (Mensual)",
    iconName: "GraduationCap",
    description: "Acompañamiento mensual para ejecutar tu estrategia.",
    price: 299,
    isPopular: true,
    code: "FUR-S-CE-003",
    furNumber: 48,
    sourceCategoryName: "Consultoría y Estrategia",
    categoryId: "directory-cat-15",
    categoryName: "Consultoría",
    categorySlug: "consultoria",
    currencyCode: "USD",
    billingPeriod: "mes",
    deliveryDays: 30,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ce-004",
    title: "Plan de Acción SEO Local",
    iconName: "ListChecks",
    description: "Plan de acción claro y detallado con prioridades y cronograma.",
    price: 129,
    isPopular: false,
    code: "FUR-S-CE-004",
    furNumber: 49,
    sourceCategoryName: "Consultoría y Estrategia",
    categoryId: "directory-cat-15",
    categoryName: "Consultoría",
    categorySlug: "consultoria",
    currencyCode: "USD",
    billingPeriod: "único",
    deliveryDays: 5,
    relationType: "primary",
    isPrimaryCategory: true
  },
  {
    id: "fur-s-ce-005",
    title: "Revisión Estratégica Trimestral",
    iconName: "RefreshCw",
    description: "Revisión y ajustes estratégicos cada trimestre.",
    price: 149,
    isPopular: false,
    code: "FUR-S-CE-005",
    furNumber: 50,
    sourceCategoryName: "Consultoría y Estrategia",
    categoryId: "directory-cat-15",
    categoryName: "Consultoría",
    categorySlug: "consultoria",
    currencyCode: "USD",
    billingPeriod: "trimestre",
    deliveryDays: 90,
    relationType: "primary",
    isPrimaryCategory: true
  }
];

export const SPECIAL_OFFERS: Offer[] = [
  {
    id: 'off-1',
    title: 'Pack Lanzamiento Todo-en-Uno',
    description: 'Todo lo necesario para iniciar tu presencia digital local: configuración de ficha, 15 citaciones clave y 1 auditoría express.',
    originalPrice: 499,
    discountedPrice: 399,
    badge: '20% DESCUENTO'
  },
  {
    id: 'off-2',
    title: 'Auditoría + Fusión GMB Especial',
    description: 'Revisión minuciosa de errores técnicos junto con la curación de fíchas duplicadas y optimización de palabras clave.',
    originalPrice: 299,
    discountedPrice: 199,
    badge: 'OFERTA FLASH'
  }
];

export const BENEFIT_CARDS = [
  {
    id: 'ben-1',
    icon: 'ShieldCheck',
    title: 'Agencias Verificadas',
    description: 'Solo listamos y trabajamos con agencias seleccionadas que aportan pruebas claras de rankings, auditoría real y soporte ético.'
  },
  {
    id: 'ben-2',
    icon: 'CreditCard',
    title: 'Pago Protegido Escrow',
    description: 'Tu dinero se retiene de forma totalmente segura. Solo se libera a la agencia una vez das el visto bueno a los hitos entregados.'
  },
  {
    id: 'ben-3',
    icon: 'MessageSquareCode',
    title: 'Soporte Directo y Conciliación',
    description: 'Nuestro equipo de especialistas en marketing media de forma ágil e imparcial ante cualquier disputa o duda en el proyecto.'
  }
];
